#!/usr/bin/env bash

pipe_file=$1
pipe_section=$2

while true; do
    output=$(acpi -b | cut -d ' ' -f 4 | tr -d [,])

    echo "$pipe_section $(icon 'battery') $output" > $pipe_file

    sleep 5m
done
