#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )"

. .dzenbarrc

rm -f $PIPE
mkfifo $PIPE
tail -f $PIPE | dmplex | dzen2 -x $X -y $Y -w $WIDTH -h $HEIGHT -bg $BG -fg $FG -ta c -fn $FONT -p &
./cpu 1 &
./sensors 2 &
./memory 3 &
./filesystem 4 &
./network 5 &
./mcabber 6 &
./weather 7 &
#./mail 8 &
./volume 9 &
#./battery 10 &
#./mpd 11 &
