#!/usr/bin/env bash

# ./dzenbar
#
# deps: dzen2
# cfg: .dzenbarrc
# author: @qbbr

SOURCE="${BASH_SOURCE[0]}"

while [[ -h "${SOURCE}" ]]; do
	DIR="$(cd -P "$(dirname "${SOURCE}")" && pwd)"
	SOURCE="$(readlink "${SOURCE}")"
	[[ $SOURCE != /* ]] && SOURCE="${DIR}/${SOURCE}"
done

cd "$(dirname "${SOURCE}")"

. .dzenbarrc

preparePipeFile() {
	# $1 - monitor
	local PIPE_FILE=$(getPipeFilePath $1)
	local MAX_LINES=32
	# erase pipe file
	> ${PIPE_FILE}
	# fill empty lines for sed
	for ((LINE = 0; LINE < ${MAX_LINES}; LINE++)); do
		echo "" >> ${PIPE_FILE}
	done
}

echo "" > ${PIDS_FILE}

for ((monitor = 0; monitor < ${#SCRPTS[@]}; monitor++)); do
	PIPE_FILE=$(getPipeFilePath ${monitor})
	preparePipeFile "${monitor}"

	line=1
	for SCRIPT in ${SCRPTS[${monitor}]}; do
		. ./mod_${SCRIPT} ${monitor} ${line} &
		echo $! >> ${PIDS_FILE}
		((++line))
	done

	((xs = monitor + 1))
	(while true; do CONTENT=$(sed -e ':a' -e 'N' -e '$!ba' -e 's/\n//g' ${PIPE_FILE}); echo -e ${CONTENT}; sleep 1; done) | dzen2 -xs $xs -e 'button3=;' -w $WIDTH -h $HEIGHT -x $X -y $Y -fn $FONT -bg $BG_COLOR -fg $FG_COLOR -p -title-name dzenbar &
	echo $! >> ${PIDS_FILE}
done
