#!/bin/bash

. .dzenbarrc

while true; do
	OUTPUT=''
	_CACHE=`df -h`

	COUNT=${#FILESYSTEMS[@]}
	i=0
	let "COUNT = $COUNT - 1"
	for key in ${!FILESYSTEMS[@]}; do
		OUTPUT=$OUTPUT$(text $key)
		FS_DFC=`echo "$_CACHE" | grep "${FILESYSTEMS[$key]}"`

		OUTPUT="$OUTPUT `echo "$FS_DFC" | awk '{ print $5 }'`"
		OUTPUT=$OUTPUT$(text ' (')
		OUTPUT=$OUTPUT"`echo "$FS_DFC" | awk '{ print $4 }'`"
		OUTPUT=$OUTPUT$(text ')')

		if [ "$i" != "$COUNT" ]; then
			OUTPUT=$OUTPUT$(text ', ')
		fi

		let "i = $i + 1"
	done

	echo "$1 $(icon 'tall') $OUTPUT" > $PIPE

	sleep 60
done
