#!/usr/bin/env bash

pipe_file=$1
pipe_section=$2

while true; do
    output=''
    cache=`df -h`

    count=${#filesystem_disk_list[@]}
    ((--count))
    i=0

    for key in ${!filesystem_disk_list[@]}; do
        output="${output}$(text $key)"
        fs_dfc=$(echo "${cache}" | grep "${filesystem_disk_list[$key]}")

        output="${output} $(echo $fs_dfc | awk '{ print $5 }')"
        output="${output} $(text '(')"
        output="${output}$(echo $fs_dfc | awk '{ print $4 }')"
        output="${output}$(text ')')"

        if [[ "$i" != "$count" ]]; then
            output="${output}$(text ', ')"
        fi

        ((i++))
    done

    echo "$pipe_section $(decor_arrow $(icon 'tall')) $output" > $pipe_file

    sleep 60
done
