#!/usr/bin/env bash

SOURCE="${BASH_SOURCE[0]}"

while [[ -h "${SOURCE}" ]]; do
	DIR="$(cd -P "$(dirname "${SOURCE}")" && pwd)"
	SOURCE="$(readlink "${SOURCE}")"
	[[ $SOURCE != /* ]] && SOURCE="${DIR}/${SOURCE}"
done

cd "$(dirname "${SOURCE}")"

. .dzenbarrc

$(kill $(cat ${PIDS_FILE}))
