#!/usr/bin/env bash

pipe_file=$1
pipe_section=$2

while true; do
    count=`ls -1 ${maildir} | wc -l`
    if [ "$count" = 0 ]; then
        output=$(text $count)
    else
        output=$count
    fi
    echo "$pipe_section $(decor_blue $(icon 'mail')) $output" > $pipe_file

    sleep 10
done
