#!/usr/bin/env bash

pipe_file=$1
pipe_section=$2

mcabber_state="$HOME/.mcabber/mcabber.state"

while true; do
    if [ -f $mcabber_state ]
    then
        count=`cat $mcabber_state | wc -l`
    else
        count=$(text 0)
    fi
    
    echo "$pipe_section $(decor_arrow $(icon 'mail')) $count" > $pipe_file
    sleep 1
done
