#!/usr/bin/env bash

pipe_file=$1
pipe_section=$2

while true; do
    cache=`free -m`
    mem_usage_percent=`echo -e "$cache" | awk '/Mem:/ {print int($3 * 100 / $2)}'`
    mem_usage_mb=`echo -e "$cache" | awk '/Mem:/ {print $3}'`

    echo "${pipe_section} $(decor_blue $(icon 'mem')) ${mem_usage_percent}% $(text '(')"${mem_usage_mb}"M$(text ')')" > $pipe_file

    sleep 5
done
