#!/usr/bin/env bash

. .dzenbarrc

MONITOR=${1}
PIPE_LINE=${2}

while true; do
	count=$(find ${MAIL_DIR}/*/INBOX/new/ -type f | wc -l)

	if [[ "${count}" = 0 ]]; then
		output="0"
	else
		output=$(textColor ${count})
	fi

	putLineToPipeFile ${MONITOR} ${PIPE_LINE} " $(iconColor 'mail') ${output}"
	sleep 30
done
