#!/usr/bin/env bash

. .dzenbarrc

MONITOR=${1}
PIPE_LINE=${2}

while true; do
	capacity="$(cat "${BATTERY}/capacity")"
	status=$(sed "s/Discharging/-/;s/Charging/+/;s/Not charging/n/;s/Unknown/u/;s/Full//" "${BATTERY}/status")

	if [[ "${BATTERY_BACKLIGHT_CONTROL_ENABLED}" == "1" ]]; then
		current_brightness=$(backlight-brightness-control --get)

		if [[ "${status}" == "-" ]]; then
			if [[ "${current_brightness}" != "${BATTERY_BACKLIGHT_DISCHARGING}" ]]; then
				backlight-brightness-control --set ${BATTERY_BACKLIGHT_DISCHARGING} 2&> /dev/null
			fi
		else
			if [[ "${current_brightness}" != "${BATTERY_BACKLIGHT_NORMAL}" ]]; then
				backlight-brightness-control --set ${BATTERY_BACKLIGHT_NORMAL} 2&> /dev/null
			fi
		fi
	fi

	if [[ "${capacity}" -le 25 ]] && [[ "${status}" == "-" ]]; then
		 status="!${status}"
	fi

	if [[ "${status}" != "" ]]; then
		status="[${status}] "
	fi

	putLineToPipeFile ${MONITOR} ${PIPE_LINE} " $(iconColor 'battery') ${status}${capacity}%"
	sleep ${BATTERY_UPDATE}
done
