#!/usr/bin/env bash

. .dzenbarrc

MONITOR=${1}
PIPE_LINE=${2}

while true; do
	output=$(ping -c 3 ${PING_DESTINATION} 2> /dev/null | awk -F '/' 'END {printf "%d", $5}')

	if [[ "${output}" = "0" ]]; then
		output=""
	else
		output=" $(iconColor 'ping') ${output} $(textColor 'ms')"
	fi

	putLineToPipeFile ${MONITOR} ${PIPE_LINE} "${output}"
	sleep 30
done
