#!/usr/bin/env bash

. .dzenbarrc

MONITOR=${1}
PIPE_LINE=${2}

while true; do
	OUTPUT=" $(iconColor 'battery') $(acpi -b | cut -d ' ' -f 4 | tr -d [,])"

	putLineToPipeFile ${MONITOR} ${PIPE_LINE} "${OUTPUT}"
	sleep 5m
done
