#!/usr/bin/env bash

. .dzenbarrc

MONITOR=${1}
PIPE_LINE=${2}

while true; do
	if [ "$(mpc | head -c 6)" = "volume" ]; then
		output="[stopped]"
	elif [ "$(mpc | sed -n '2p' | head -c 8)" = "[paused]" ]; then
		output="[paused] $(mpc | head -n 1)"
	else
		output="[playing] $(textColor "$(mpc | head -n 1)")"
	fi

	output="$(echo ${output} | sed 's;/;\\/;g' | sed 's;&;\\&;g')"

	putLineToPipeFile ${MONITOR} ${PIPE_LINE} " $(iconColor 'mpd') ${output}"

	sleep ${MUSIC_UPDATE}
done
