#!/usr/bin/env bash

. .dzenbarrc

MONITOR=${1}
PIPE_LINE=${2}

# here we remember the previous rx/tx counts
rxb=$(cat /sys/class/net/${NETWORK_INTERFACE}/statistics/rx_bytes)
txb=$(cat /sys/class/net/${NETWORK_INTERFACE}/statistics/tx_bytes)

while true; do
	# get new rx/tx counts
	rxbn=$(cat /sys/class/net/${NETWORK_INTERFACE}/statistics/rx_bytes)
	txbn=$(cat /sys/class/net/${NETWORK_INTERFACE}/statistics/tx_bytes)

	# calculate rates
	rxr=$(echo "(${rxbn} - ${rxb}) / 1024 / ${NETWORK_UPDATE}" | bc -l | xargs printf "%.2f")
	txr=$(echo "(${txbn} - ${txb}) / 1024 / ${NETWORK_UPDATE}" | bc -l | xargs printf "%.2f")

	# reset old rates
	rxb=${rxbn}
	txb=${txbn}

	output=" $(iconColor 'wired') $(iconColor 'down' '#859900') ${rxr} kBs $(iconColor 'up' '#B58900') ${txr} kBs"

	putLineToPipeFile ${MONITOR} ${PIPE_LINE} "${output}"
	sleep ${NETWORK_UPDATE}
done
