#!/usr/bin/env bash

. .dzenbarrc

MONITOR=${1}
PIPE_LINE=${2}

while true; do
	cache=$(free -m)
	mem_usage_percent=$(echo -e "$cache" | awk '/Mem:/ {print int($3 * 100 / $2)}')
	mem_usage_mb=$(echo -e "$cache" | awk '/Mem:/ {print $3}')

	output=" $(iconColor 'memory') $(textColor "${mem_usage_percent}")% ("${mem_usage_mb}"M)"

	putLineToPipeFile ${MONITOR} ${PIPE_LINE} "${output}"
	sleep ${MEMORY_UPDATE}
done
