#!/usr/bin/env bash

pipe_file=$1
pipe_section=$2

while true; do
    if [ "`mpc | head -c 6`" = "volume" ]; then
        output='[stoped]'
    elif [ "`mpc | sed -n '2p' | head -c 8`" = "[paused]" ]; then
        output='[paused]'
    else
        output=`mpc | head -n 1`
    fi

    echo "$pipe_section $(decor_blue $(icon 'mpd')) $output" > $pipe_file

    sleep 10
done
