#!/usr/bin/env bash

pipe_file=$1
pipe_section=$2

sleep=2

# here we remember the previous rx/tx counts
rxb=`cat /sys/class/net/$interface/statistics/rx_bytes`
txb=`cat /sys/class/net/$interface/statistics/tx_bytes`

while true; do
    # get new rx/tx counts
    rxbn=`cat /sys/class/net/$interface/statistics/rx_bytes`
    txbn=`cat /sys/class/net/$interface/statistics/tx_bytes`

    # calculate the rates
    # format the values to 4 digit fields
    rxr=`echo "($rxbn - $rxb) / 1024 / $sleep" | bc -l | xargs printf "%.2f"`
    txr=`echo "($txbn - $txb) / 1024 / $sleep" | bc -l | xargs printf "%.2f"`

    # reset old rates
    rxb=$rxbn; txb=$txbn

    echo "$pipe_section $(decor_blue $(icon 'wired')) ^fg($icon_network_down_color)^i($icon_path/net_down.xbm)^fg() $rxr kB/s ^fg($icon_network_up_color)^i($icon_path/net_up.xbm)^fg() $txr kB/s" > $pipe_file

    sleep $sleep
done
