#!/usr/bin/env bash

pipe_file=$1
pipe_section=$2

while true; do
    output=''
    cache=`sensors`

    count=${#sensors[@]}
    i=0
    let "count = $count - 1"
    for key in ${!sensors[@]}; do
        output="$output$(text $key)"
        _temp=`echo "$cache" | sed "${sensors[$key]}!D" | sed -ne 's/[^:]*: \+[-+]\([0-9]\+\).*/\1/p'`
        output="$output $_temp°C"
        if [ "$i" != "$count" ]; then
            output=$output$(text ', ')
        fi
        let "i = $i + 1"
    done

    echo "$pipe_section $(decor_arrow $(icon 'temp')) $output" > $pipe_file

    sleep 5
done
