#!/usr/bin/env bash

pipe_file=$1
pipe_section=$2

while true; do
    volume=`amixer get $mixer | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/'`
    volume_on=`amixer get $mixer | sed -ne 's/.*\ \[\([^]]*\).*/\1/p'`

    if [ "$volume_on" = "on" ]; then
        output="$(decor_blue $(icon 'volume'))"
    else
        output="$(decor_blue $(icon 'volume-mute'))"
    fi

    echo "$pipe_section $output $volume%" > $pipe_file

    sleep 5
done
