#!/usr/bin/env bash

pipe_file=$1
pipe_section=$2

while true; do
    cache='/tmp/weather.cache'
    weather UIII -q -m > $cache

    w_temp=`cat $cache | awk '/Temperature/ {print $2}'`
    w_humidity=`cat $cache | awk '/Humidity/ {print $3}'`
    w_sky=`cat $cache | awk '/Sky conditions/ {for(i=3;i<=NF;i++) print $i}' | sed ':a;N;$!ba;s/\n/ /g'`

    if [[ -n $w_sky ]]; then
        w_sky="$w_sky, "
    fi

    w_wind=`cat $cache | awk -F KPH '/Wind/ {print $1}' | awk '{print $NF}'`

    if [[ -n $w_wind ]]; then
        w_wind=`echo "scale=1; ${w_wind}*1000/60/60" | bc -l | awk '{printf "%.1f\n", $0}'`
        w_wind="${w_wind} mps, "
    fi

    echo "$pipe_section $(decor_blue $(icon 'load')) ${w_sky}${w_wind}$(text 't:') ${w_temp}°C$(text ', h:') ${w_humidity}" > $pipe_file

    sleep 30m
done
